#ifndef JOS_INC_QUEUE_H
#define JOS_INC_QUEUE_H

#define QUEUE_SIZE 0xa
#define FRONT_DEFAULT 0x0
#define REAR_DEFAULT 0x0
#define OP_SUCCESSFUL 0x0
#define ERROR_NOT_SUCCESSFUL 0x1
#define ERROR_QUEUE_FULL 0x12
#define ERROR_QUEUE_EMPTY 0x13

#endif